### ISSUE TITLE
Services Section

### ISSUE THREAD

**Issue by jakecrawford12** [jakecrawford12/jakecrawford12.github.io#3]
*Change “Lorem… consectetur.” to “Contact us for pricing!”*
 
First Bubble: 
     Heading: Social Media Marketing
     Description: FaceBook Advertising is the most direct way to target your audience. We target specific individuals who would likely be interested in your product or service.

Second Bubble:
     Heading: Social Media Management
     Description: With our social media marketing strategies, we not only grow your online presence, we create a story for your company.

Third Bubble:
     Heading: Web Design
     Description: Coming soon

![first_bubble_pic](https://user-images.githubusercontent.com/28963733/26859011-d0919d60-4b02-11e7-98e5-a8ab1f75b38f.jpg)
![second_bubble_pic](https://user-images.githubusercontent.com/28963733/26859012-d2361754-4b02-11e7-9372-e299cf04b24b.jpeg)

**Comment by Ernie3** [comment]
https://github.com/jakecrawford12/jakecrawford12.github.io/commit/024357df11d0ecc6cd3619b43bedf8ee8a782225
