### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by jakecrawford12** [jakecrawford12/jakecrawford12.github.io#4]
Move social media links to the right of "Premier Social" on the home page.

FaceBook: https://www.facebook.com/premiersocial22/

Instagram: https://www.instagram.com/premier_social/

Delete: "Get more leads for your company"
Center and increase the font on "Grow your online presence"

![instagram_logo](https://user-images.githubusercontent.com/28963733/26859154-cbdc0430-4b03-11e7-83a6-f1ccf707524e.png)

**Comment by Ernie3** [comment]
https://github.com/jakecrawford12/jakecrawford12.github.io/commit/024357df11d0ecc6cd3619b43bedf8ee8a782225

**Comment by Ernie3** [comment]
Moving the "Move social media links to the right of "Premier Social" on the home page" to a separate ticket, and I removed "Get more leads for your company" while increasing the size of "Grow your online presence"
