### ISSUE TITLE
Contact Us Section

### ISSUE THREAD

**Issue by jakecrawford12** [jakecrawford12/jakecrawford12.github.io#6]
Info: 
 
Email: premiersocial22@gmail.com
Phone: (267) 332-4416
 
Address:     Kennett Square, PA
	        United States of America

**Comment by Ernie3** [comment]
Will need to be refined later, did the best I could in one night
https://github.com/jakecrawford12/jakecrawford12.github.io/commit/9aef491040c1f0f00861f35e053d0aeb2888dba9
