### ISSUE TITLE
About Section

### ISSUE THREAD

**Issue by jakecrawford12** [jakecrawford12/jakecrawford12.github.io#7]
About Us:

Hello, we are Premier Social, a Digital Marketing Agency. We help build brand awareness for various businesses using social media. Whether it’s online advertising or social media management we got you covered. Email us for a free business audit!

Background Image:
![about_us_photo](https://user-images.githubusercontent.com/28963733/27159559-ec021568-513b-11e7-86b2-2eb6d7046060.jpg)

**Comment by Ernie3** [comment]
Again might need to be refined later, but best I could do for one night
https://github.com/jakecrawford12/jakecrawford12.github.io/commit/9aef491040c1f0f00861f35e053d0aeb2888dba9
